package bpe

import (
	"bytes"
	_ "embed"
	"encoding/binary"
	"errors"
	"fmt"
	"sync"
)

// The vocabulary blob. Generated by gen/generate_vocab.py; see doc.go and the
// generator's module docstring for the layout and for why it is a binary blob
// rather than a Go source literal.
//
//go:embed cl100k_base.bin
var vocabBlob []byte

// blobMagic identifies the container so a stale or truncated .bin fails loudly
// instead of producing silently wrong token counts.
const blobMagic = "NBPE"

const (
	blobVersion = 1
	headerSize  = 16 // magic[4] + version, n, maxLen (uint32 LE each)
)

// tableBits sizes the open-addressed lookup table. 2^17 slots for 100_256
// entries is a load factor of 0.765: about 2.6 probes for a hit, 9.5 for a
// miss, against 512 KiB of resident memory. Dropping to 2^16 would not fit;
// going to 2^18 would double the table to save roughly one probe on a hit.
const (
	tableBits = 17
	tableSize = 1 << tableBits
	tableMask = tableSize - 1
)

// ErrUnavailable reports that the embedded vocabulary could not be decoded.
//
// This is a build defect rather than a runtime condition, but the reference
// tolerates an unusable tokenizer by falling back to a byte heuristic, so the
// error is propagated rather than panicked. See agent.EstimatePromptTokens.
var ErrUnavailable = errors.New("bpe: cl100k_base vocabulary unavailable")

// SpecialTokenError mirrors the ValueError tiktoken raises when the text
// contains a special token and `disallowed_special` was not relaxed.
type SpecialTokenError struct {
	// Token is the offending special token string.
	Token string
}

func (e *SpecialTokenError) Error() string {
	return fmt.Sprintf("bpe: encountered special token %q in input (disallowed_special=all)", e.Token)
}

// specialTokens is Encoding.special_tokens for cl100k_base, in the order
// openai_public.py declares them. Decode uses the values; Encode checks for the
// keys. The order does not affect matching because no token is a prefix of
// another.
var specialTokens = []struct {
	text string
	rank uint32
}{
	{"<|endoftext|>", 100257},
	{"<|fim_prefix|>", 100258},
	{"<|fim_middle|>", 100259},
	{"<|fim_suffix|>", 100260},
	{"<|endofprompt|>", 100276},
}

// NVocab is Encoding.n_vocab for cl100k_base.
const NVocab = 100277

// vocabulary is the decoded, in-memory form of the blob.
//
// Everything here is built once, lazily. `tokens` aliases the embedded blob
// (no copy); `offs` and `table` are the only heap allocations the encoder
// makes, 401_028 and 524_288 bytes respectively.
type vocabulary struct {
	// tokens is every mergeable rank's bytes, concatenated in rank order.
	tokens []byte
	// offs has len(tokens)+1 entries; rank i's bytes are
	// tokens[offs[i]:offs[i+1]].
	offs []uint32
	// table is an open-addressed set of (rank+1) values, 0 meaning empty.
	table []uint32
}

var (
	vocabOnce sync.Once
	vocabVal  *vocabulary
	vocabErr  error
)

// getVocab returns the shared encoder, decoding the blob on first use.
//
// Lazy is a requirement, not an optimisation: token estimation only runs on the
// compaction and archival paths, so a process that never compacts must not pay
// the ~1.6 MiB the encoder costs.
func getVocab() (*vocabulary, error) {
	vocabOnce.Do(func() { vocabVal, vocabErr = loadVocab(vocabBlob) })
	return vocabVal, vocabErr
}

func loadVocab(blob []byte) (*vocabulary, error) {
	if len(blob) < headerSize {
		return nil, fmt.Errorf("%w: blob is %d bytes, shorter than the %d-byte header",
			ErrUnavailable, len(blob), headerSize)
	}
	if string(blob[0:4]) != blobMagic {
		return nil, fmt.Errorf("%w: bad magic %q", ErrUnavailable, blob[0:4])
	}
	version := binary.LittleEndian.Uint32(blob[4:8])
	if version != blobVersion {
		return nil, fmt.Errorf("%w: blob version %d, want %d", ErrUnavailable, version, blobVersion)
	}
	n := int(binary.LittleEndian.Uint32(blob[8:12]))
	maxLen := binary.LittleEndian.Uint32(blob[12:16])
	if n <= 0 || n >= tableSize {
		return nil, fmt.Errorf("%w: %d ranks does not fit a %d-slot table", ErrUnavailable, n, tableSize)
	}
	if maxLen > 255 {
		return nil, fmt.Errorf("%w: max token length %d does not fit uint8", ErrUnavailable, maxLen)
	}
	if len(blob) < headerSize+n {
		return nil, fmt.Errorf("%w: truncated length table", ErrUnavailable)
	}
	lengths := blob[headerSize : headerSize+n]
	tokens := blob[headerSize+n:]

	v := &vocabulary{
		tokens: tokens,
		offs:   make([]uint32, n+1),
		table:  make([]uint32, tableSize),
	}
	var off uint32
	for i := 0; i < n; i++ {
		v.offs[i] = off
		off += uint32(lengths[i])
	}
	v.offs[n] = off
	if int(off) != len(tokens) {
		return nil, fmt.Errorf("%w: length table sums to %d, blob holds %d token bytes",
			ErrUnavailable, off, len(tokens))
	}

	for i := 0; i < n; i++ {
		tok := tokens[v.offs[i]:v.offs[i+1]]
		if len(tok) == 0 {
			return nil, fmt.Errorf("%w: rank %d is empty", ErrUnavailable, i)
		}
		h := hashBytes(tok) & tableMask
		for v.table[h] != 0 {
			h = (h + 1) & tableMask
		}
		v.table[h] = uint32(i) + 1
	}
	return v, nil
}

// hashBytes is FNV-1a followed by the MurmurHash3 finaliser.
//
// FNV-1a alone is a poor fit here: its low bits are the least mixed, and the
// table index is taken from the low bits of a power-of-two mask. The finaliser
// costs two multiplies and makes the masked bits uniform.
func hashBytes(b []byte) uint32 {
	h := uint32(2166136261)
	for _, c := range b {
		h ^= uint32(c)
		h *= 16777619
	}
	h ^= h >> 16
	h *= 0x7feb352d
	h ^= h >> 15
	h *= 0x846ca68b
	h ^= h >> 16
	return h
}

// rank returns the merge priority of tok, or ok=false when tok is not a token.
//
// tiktoken's CoreBPE.encoder is a HashMap<Vec<u8>, Rank>; this is the same
// relation with an open-addressed table over the embedded blob.
func (v *vocabulary) rank(tok []byte) (uint32, bool) {
	h := hashBytes(tok) & tableMask
	for {
		e := v.table[h]
		if e == 0 {
			return 0, false
		}
		i := e - 1
		if bytes.Equal(v.tokens[v.offs[i]:v.offs[i+1]], tok) {
			return i, true
		}
		h = (h + 1) & tableMask
	}
}

// token returns the bytes of rank i. It reports false for a rank outside the
// mergeable vocabulary.
func (v *vocabulary) token(i uint32) ([]byte, bool) {
	if int(i) >= len(v.offs)-1 {
		return nil, false
	}
	return v.tokens[v.offs[i]:v.offs[i+1]], true
}

// NumRanks reports how many mergeable ranks the vocabulary holds (100_256 for
// cl100k_base). It exists for tests and diagnostics.
func NumRanks() (int, error) {
	v, err := getVocab()
	if err != nil {
		return 0, err
	}
	return len(v.offs) - 1, nil
}

// Available reports whether the embedded vocabulary can be decoded.
//
// It is the Go counterpart of `_get_token_encoding()` succeeding: callers that
// want to fall back to a byte heuristic rather than propagate an error use it
// to decide. The first call pays the decode.
func Available() bool {
	_, err := getVocab()
	return err == nil
}
