package api

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/adrianolimagarcia/nanobot-go/internal/config"
)

// configTargetPath returns the exact config file that owns the running
// configuration. This is important for installations still using the legacy
// ~/.nanobot/config.json path: saving through the WebUI must update that file,
// not silently fork state into a second ~/.haosbot/config.json.
func configTargetPath(cfg *config.Config) string {
	if cfg != nil {
		if source := strings.TrimSpace(cfg.SourcePath()); source != "" {
			return source
		}
	}
	return config.DefaultConfigPath()
}

// redactedConfig returns a JSON-compatible configuration view without secret
// values. For every redacted field a sibling <field>Configured boolean is added
// so the WebUI can show whether a credential already exists without receiving it.
func redactedConfig(cfg *config.Config) (map[string]any, error) {
	if cfg == nil {
		return nil, fmt.Errorf("nil config")
	}
	raw, err := json.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	var out map[string]any
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, err
	}
	redactMap(out)
	return out, nil
}

func redactMap(m map[string]any) {
	for key, value := range m {
		if isSecretKey(key) {
			configured := secretConfigured(value)
			m[key] = ""
			m[key+"Configured"] = configured
			continue
		}
		switch child := value.(type) {
		case map[string]any:
			redactMap(child)
		case []any:
			redactSlice(child)
		}
	}
}

func redactSlice(items []any) {
	for _, item := range items {
		switch child := item.(type) {
		case map[string]any:
			redactMap(child)
		case []any:
			redactSlice(child)
		}
	}
}

func isSecretKey(key string) bool {
	k := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(key, "-", ""), "_", ""))
	switch k {
	case "apikey", "token", "secret", "password", "authorization", "auth":
		return true
	default:
		return false
	}
}

func secretConfigured(v any) bool {
	switch x := v.(type) {
	case nil:
		return false
	case string:
		return strings.TrimSpace(x) != ""
	default:
		return true
	}
}

// saveConfigPatch merges a partial WebUI update into the current typed config,
// validates the merged document by loading it through the canonical config
// decoder, and persists it through Config.Save (atomic temp+fsync+rename).
// Blank secret fields intentionally keep the existing secret so a redacted GET
// followed by POST cannot erase credentials.
func saveConfigPatch(current *config.Config, target string, patch map[string]any) error {
	if current == nil {
		return fmt.Errorf("nil current config")
	}
	baseRaw, err := json.Marshal(current)
	if err != nil {
		return err
	}
	var base map[string]any
	if err := json.Unmarshal(baseRaw, &base); err != nil {
		return err
	}
	mergeConfigMap(base, patch)

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(target), ".config-validate-*.json")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return err
	}
	enc := json.NewEncoder(tmp)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(base); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	validated, err := config.Load(tmpName)
	if err != nil {
		return err
	}
	return validated.Save(target)
}

func mergeConfigMap(dst, patch map[string]any) {
	for key, incoming := range patch {
		// Ignore UI-only metadata generated by redactedConfig.
		if strings.HasSuffix(key, "Configured") {
			continue
		}
		if isSecretKey(key) && blankSecret(incoming) {
			continue
		}
		incomingMap, incomingIsMap := incoming.(map[string]any)
		if incomingIsMap {
			if existingMap, ok := dst[key].(map[string]any); ok {
				mergeConfigMap(existingMap, incomingMap)
				continue
			}
		}
		dst[key] = incoming
	}
}

func blankSecret(v any) bool {
	if v == nil {
		return true
	}
	if s, ok := v.(string); ok {
		s = strings.TrimSpace(s)
		return s == "" || s == "********" || s == "••••••••"
	}
	return false
}
