(() => {
'use strict';
const auth=(extra={})=>typeof window.webuiAuthHeaders==='function'?window.webuiAuthHeaders(extra):extra;
function e(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function rows(payload){if(Array.isArray(payload))return payload;if(!payload||typeof payload!=='object')return[];for(const k of ['skills','results','items','data'])if(Array.isArray(payload[k]))return payload[k];if(payload.data&&typeof payload.data==='object')for(const k of ['skills','results','items'])if(Array.isArray(payload.data[k]))return payload.data[k];return[]}
function norm(x){const source=x.source||x.repository||x.repo||x.github||x.ownerRepo||'';return{name:String(x.name||x.skill||x.slug||x.id||''),source:String(source),description:String(x.description||x.summary||'')}}
function ensure(){if(document.getElementById('skills-marketplace-button'))return;const nav=document.querySelector('.nanobot-utility-nav')||document.querySelector('aside');if(!nav)return;const b=e('button','sidebar-action','Marketplace');b.id='skills-marketplace-button';b.type='button';b.onclick=open;nav.append(b)}
async function load(q,provider,body,status){status.textContent='Carregando…';body.replaceChildren();const r=await fetch('/api/webui/skills/marketplace?provider='+encodeURIComponent(provider)+'&q='+encodeURIComponent(q||''),{headers:auth()});if(!r.ok){status.textContent=await r.text();return}const d=await r.json();status.textContent=d.install_supported?'Instalação habilitada':'Instalação desabilitada';const list=rows(d.payload).map(norm).filter(x=>x.name);if(!list.length){body.append(e('div','session-loading','Nenhum skill encontrado.'));return}for(const item of list.slice(0,80)){const row=e('div','market-skill-row'),info=e('div');info.append(e('strong','',item.name),e('div','control-muted',item.description||item.source||''));const install=e('button','control-button primary','Instalar');install.disabled=!d.install_supported||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(item.source);install.onclick=async()=>{install.disabled=true;install.textContent='Instalando…';const x=await fetch('/api/webui/skills/install',{method:'POST',headers:auth({'Content-Type':'application/json'}),body:JSON.stringify({source:item.source,skill:item.name})});if(!x.ok){status.textContent=await x.text();install.textContent='Falhou';install.disabled=false;return}install.textContent='Instalado';window.dispatchEvent(new CustomEvent('haosbot:turn-complete'))};row.append(info,install);body.append(row)}}
function open(){let modal=document.getElementById('skills-marketplace-modal');if(modal){modal.classList.remove('hidden');return}modal=e('div','market-modal');modal.id='skills-marketplace-modal';const card=e('div','market-card'),top=e('div','market-top');top.append(e('strong','','Skills Marketplace'));const close=e('button','control-button','Fechar');close.onclick=()=>modal.classList.add('hidden');top.append(close);const controls=e('div','control-toolbar'),q=e('input','control-input');q.placeholder='Buscar skills';const provider=e('select','control-input');['skills_sh','skillhub'].forEach(v=>{const o=e('option','',v);o.value=v;provider.append(o)});const search=e('button','control-button primary','Buscar'),status=e('span','control-muted','');controls.append(q,provider,search,status);const body=e('div','market-results');search.onclick=()=>load(q.value,provider.value,body,status);q.onkeydown=ev=>{if(ev.key==='Enter')load(q.value,provider.value,body,status)};card.append(top,controls,body);modal.append(card);document.body.append(modal);load('',provider.value,body,status)}
window.addEventListener('DOMContentLoaded',ensure);ensure();
})();