package main

import (
	"context";"os";"path/filepath";"regexp";"strings";"time"
	"github.com/adrianolimagarcia/nanobot-go/internal/agent"
	"github.com/adrianolimagarcia/nanobot-go/internal/config"
	"github.com/adrianolimagarcia/nanobot-go/internal/core"
	cronruntime "github.com/adrianolimagarcia/nanobot-go/internal/cron"
	"github.com/adrianolimagarcia/nanobot-go/internal/memory"
)
const systemHeartbeatJobID="__haosbot_heartbeat"
const systemDreamJobID="__haosbot_dream"
func configureSystemAutomations(cfg *config.Config,workspace string,scheduler *cronruntime.Service)error{if cfg.Gateway.Heartbeat.Enabled{seconds:=cfg.Gateway.Heartbeat.IntervalS;if seconds<=0{seconds=1800};ms:=int64(seconds)*1000;if _,err:=scheduler.UpsertSystemJob(cronruntime.Job{ID:systemHeartbeatJobID,Name:"Heartbeat",Schedule:cronruntime.Schedule{Kind:cronruntime.KindEvery,EveryMS:&ms},Payload:cronruntime.Payload{Kind:cronruntime.PayloadSystemEvent,SystemEvent:"heartbeat"},TimeoutMS:int64((5*time.Minute)/time.Millisecond),MisfirePolicy:cronruntime.MisfireSkip});err!=nil{return err}};dream:=cfg.Agents.Defaults.Dream;if dream.Enabled{var schedule cronruntime.Schedule;if dream.Cron!=nil&&strings.TrimSpace(*dream.Cron)!=""{tz:=cfg.Agents.Defaults.Timezone;if strings.TrimSpace(tz)==""{tz="UTC"};schedule=cronruntime.Schedule{Kind:cronruntime.KindCron,Expr:strings.TrimSpace(*dream.Cron),TZ:tz}}else{hours:=dream.IntervalH;if hours<=0{hours=24};ms:=int64(hours)*int64(time.Hour/time.Millisecond);schedule=cronruntime.Schedule{Kind:cronruntime.KindEvery,EveryMS:&ms}};if _,err:=scheduler.UpsertSystemJob(cronruntime.Job{ID:systemDreamJobID,Name:"Dream",Schedule:schedule,Payload:cronruntime.Payload{Kind:cronruntime.PayloadSystemEvent,SystemEvent:"dream"},TimeoutMS:int64((15*time.Minute)/time.Millisecond),MisfirePolicy:cronruntime.MisfireFireOnce});err!=nil{return err}};return nil}
func executeSystemAutomation(ctx context.Context,loop *agent.Loop,workspace string,job cronruntime.Job,runID string)(cronruntime.RunResult,error){switch job.Payload.SystemEvent{case"heartbeat":content,err:=os.ReadFile(filepath.Join(workspace,"HEARTBEAT.md"));if err!=nil{return cronruntime.RunResult{RunID:runID},err};if !heartbeatHasTasks(string(content)){return cronruntime.RunResult{RunID:runID},cronruntime.SkippedError{Reason:"heartbeat: no active tasks"}};key:="system:heartbeat";role:="user";out,err:=loop.ProcessMessage(ctx,core.InboundMessage{Channel:"system",SenderID:"heartbeat",ChatID:"heartbeat",Content:"Heartbeat check. Execute the active tasks in HEARTBEAT.md. Stay quiet when no action or report is needed.",SessionKeyOverride:&key,InputRole:&role,Metadata:map[string]any{"_system_event":"heartbeat","run_id":runID}});if err!=nil{return cronruntime.RunResult{RunID:runID},err};if out!=nil{return cronruntime.RunResult{RunID:runID,Response:out.Content},nil};return cronruntime.RunResult{RunID:runID},nil;case"dream":store,err:=memory.NewMemoryStore(workspace,memory.DefaultMaxHistory);if err!=nil{return cronruntime.RunResult{RunID:runID},err};p,last,ok,err:=store.BuildDreamPrompt(200);if err!=nil{return cronruntime.RunResult{RunID:runID},err};if !ok{return cronruntime.RunResult{RunID:runID},cronruntime.SkippedError{Reason:"dream: no unprocessed history"}};key:=memory.DreamSessionKey();chat:=strings.TrimPrefix(key,"dream:");role:="user";out,err:=loop.ProcessMessage(ctx,core.InboundMessage{Channel:"dream",SenderID:"dream",ChatID:chat,Content:p,SessionKeyOverride:&key,InputRole:&role,Metadata:map[string]any{"_system_event":"dream","run_id":runID}});if err!=nil{return cronruntime.RunResult{RunID:runID},err};if !memory.DreamRunCompleted(out){return cronruntime.RunResult{RunID:runID},cronruntime.SkippedError{Reason:memory.DreamIncompletionReason(out)}};if err:=store.SetLastDreamCursor(last);err!=nil{return cronruntime.RunResult{RunID:runID},err};_ = store.CompactHistory();response:="";if out!=nil{response=out.Content};return cronruntime.RunResult{RunID:runID,Response:response},nil;default:return cronruntime.RunResult{RunID:runID},cronruntime.SkippedError{Reason:"unknown system event"}}}
var heartbeatCommentRE=regexp.MustCompile(`(?s)<!--.*?-->`)
func heartbeatHasTasks(content string)bool{clean:=heartbeatCommentRE.ReplaceAllString(content,"");for _,line:=range strings.Split(clean,"\n"){line=strings.TrimSpace(line);if line==""||strings.HasPrefix(line,"#"){continue};return true};return false}
